name: devbuild
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Remove *-dev.jar
        run: rm ./build/libs/*-dev.jar
      - name: Rename build artifacts
        run: mv build/libs/*.jar build/libs/ItemFrameDupe.jar
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Dev Build
          path: build/libs/ItemFrameDupe.jar
